version: "3.8"
services:

  # relay:
  #   build:
  #     context: ../
  #     dockerfile: ./basic/Dockerfile
  #   environment:
  #     PORT: 2700
  #     POSTGRESQL_DATABASE: postgres://nostr:nostr@postgres:5432/nostr?sslmode=disable
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - 2700:2700
  #   command: "./basic/relayer-basic"
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    restart: always
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms${ES_MEM:-4g} -Xmx${ES_MEM:-4g}"
    ports:
      - '127.0.0.1:9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        ["CMD-SHELL", "curl --silent --fail elasticsearch:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


